# Generated by Django 4.1.7 on 2023-03-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wow', '0002_alter_item_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactiontype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='playableclass',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='playablerace',
            name='faction',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='playablerace',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
